# Numpy Exercises

In [1]:
import numpy as np
import pandas as pd

* How to stack two array vertically?

In [5]:
a = np.arange(0, 10).reshape(2, 5)
b = np.arange(10, 20).reshape(2, 5)

In [6]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
b

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [8]:
np.vstack((a, b))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

* How to generate custion sequences in numpy without hardcoding?

In [9]:
a = np.array([1, 2, 3])
# desired output: [1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
output = np.hstack((np.repeat(a, 3), a, a, a))

In [10]:
a

array([1, 2, 3])

In [11]:
output

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

* How to get the common items between two python numpy arrays?

In [12]:
a = np.arange(0, 10)
b = np.array([2, 11, 5, 4, 3, 19, 20])

In [13]:
np.intersect1d(a, b)

array([2, 3, 4, 5])

* How to remove from one array those items that exist in another?

In [16]:
a = np.array([1, 3, 4, 6, 8])
b = np.array([3, 7, 4, 9, 10])
# desired output : [1, 6, 8]

In [45]:
out = list(filter(lambda i : i not in b, a))

In [43]:
out

[1, 6, 8]

* How to get the positions where elements of two arrays match?

In [59]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 2, 6, 4, 5])
# desired output : [1, 3, 4]

In [60]:
np.where(a == b)

(array([1, 3, 4]),)

* How to extract all numbers between a given range from a numpy array?

In [63]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
# desired output : [6, 9, 10]

In [65]:
a[(a > 5) & (a <= 10)]

array([ 6,  9, 10])

*  How to swap two columns in a 2d numpy array?

In [85]:
a = np.arange(9).reshape(3, 3)

In [86]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [87]:
# swap first and second columns.
a[:, [0, 1]] = a[:, [1, 0]]

In [88]:
a

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

#### Second way of swap:

In [82]:
b = np.arange(9).reshape(3,3)
temp = b[:, 0].copy()

In [83]:
b[:, 0] = b[:, 1]
b[:, 1] = temp

In [84]:
b

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

* How to swap two rows in a 2d numpy array?

In [90]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [91]:
a[[0, 1], :] = a[[1, 0], :]

In [92]:
a

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

#### Second way:

In [93]:
b = np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [96]:
temp = b[0, :].copy()
b[0, :] = b[1, :]
b[1, :] = temp

In [97]:
b

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

* How to reverse the rows of a 2d array?

In [102]:
a = np.arange(10).reshape(2, 5)

In [103]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [104]:
a[: :-1]

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

* How to create a 2D array containing random floats between 5 and 10?

In [106]:
np.random.randint(5, 11, 15).reshape(5, 3)

array([[ 5,  9,  8],
       [ 6, 10,  8],
       [ 9,  6,  5],
       [ 9,  9,  9],
       [ 9, 10,  6]])

*  How to print only 3 decimal places in python numpy array?

In [107]:
rand = np.random.random((5, 3))
rand

array([[0.72896543, 0.20464541, 0.23662026],
       [0.47841687, 0.77462495, 0.42243326],
       [0.84636151, 0.36375953, 0.19408858],
       [0.06345854, 0.79490642, 0.59006326],
       [0.23136953, 0.34533815, 0.67175898]])

In [116]:
np.set_printoptions(precision=3) # default 8.

In [117]:
rand

array([[0.729, 0.205, 0.237],
       [0.478, 0.775, 0.422],
       [0.846, 0.364, 0.194],
       [0.063, 0.795, 0.59 ],
       [0.231, 0.345, 0.672]])