We'll need to import numpy to get started.

In [1]:
import numpy as np

### Numpy Arrays

#### A numpy array is a grid of the same type and indexed values. To create an array with numpy:

In [2]:
arr = np.array([1, 2, 3, 4, 5])

In [3]:
type(arr)

numpy.ndarray

Also, you can create a matrix with numpy.

In [4]:
matr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [5]:
type(matr)

numpy.ndarray

In [6]:
matr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
matr.shape

(3, 3)

#### Creating Arrays

numpy arange() is one of the array creation way, return evenly spaced values within a given interval. (NumPy docs)

#### np.arange(start, stop, step)

In [8]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [12]:
# Create an array full of zeros with shape (2, 2)
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [13]:
# Create an array full of ones
np.ones(3)

array([1., 1., 1.])

In [17]:
# Array of 6 evenly divided values from 0 to 30
np.linspace(0, 30, 6)

array([ 0.,  6., 12., 18., 24., 30.])

In [19]:
# Array of 0 with 1 on diagonal
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
# (4, 5) array of random floats between 0-1
np.random.rand(3, 4)

array([[0.64102698, 0.10775651, 0.46245396, 0.13004939],
       [0.86218997, 0.89669649, 0.06024992, 0.44299575],
       [0.88317177, 0.27885313, 0.88255162, 0.59875708]])

In [23]:
# Return random integers from low to high
np.random.randint(0, 10, 6)

array([5, 1, 4, 0, 3, 6])

* reshape() method gives a new shape to an array without changinh its data.

In [24]:
arr = np.arange(10)

In [29]:
arr.reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
arr.max()

9

In [31]:
arr.min()

0

In [33]:
# Returns the indices of the max values
arr.argmax()

9

In [34]:
# Return the indices of the min values
arr.argmin()

0

#### Index Slicing

In [35]:
arr = np.array(['apple', 'banana', 'watermelon'])

In [36]:
arr[1] # second row of the array

'banana'

In [63]:
arr = np.arange(0, 20)

In [64]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
# arr[start:stop:step]
arr[3:7:2]

array([3, 5])

In [42]:
arr[3:8] = -5

In [43]:
arr

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [44]:
arr[3:8] = [3, 4, 5, 6, 7]

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

* Main array will change the way you change sub_array.

In [65]:
sub_arr = arr[2:5]

In [66]:
sub_arr

array([2, 3, 4])

In [67]:
sub_arr[:] = 50

In [68]:
sub_arr

array([50, 50, 50])

In [69]:
arr

array([ 0,  1, 50, 50, 50,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

If you dont want your main array to change you can get a copy.

* arr_copy = arr.copy()

In [80]:
matr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [81]:
matr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [82]:
matr[0] # first row of the matrix

array([10, 20, 30])

In [84]:
matr[1][2] # third entry of the second row. Same as matr[1, 2].

60

In [85]:
matr[1:, 2] # second and third rows' third column

array([60, 90])

In [86]:
matr[2:, 0:]

array([[70, 80, 90]])

In [88]:
matr[[0, 2]] # first and third row

array([[10, 20, 30],
       [70, 80, 90]])

#### numpy operations

In [92]:
arr = np.random.randint(1, 50, 20)

In [93]:
arr

array([44,  6, 20,  3, 29, 33, 36, 35, 31, 25,  5,  5, 14, 38,  1, 19, 11,
       18, 36, 22])

In [94]:
arr < 10

array([False,  True, False,  True, False, False, False, False, False,
       False,  True,  True, False, False,  True, False, False, False,
       False, False])

In [95]:
arr[arr < 10] # Easiest way

array([6, 3, 5, 5, 1])